[2025-03-26T03:30:09.283+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T03:30:09.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:25:35.827118+00:00 [queued]>
[2025-03-26T03:30:09.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:25:35.827118+00:00 [queued]>
[2025-03-26T03:30:09.360+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T03:30:09.385+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_into_clickhouse> on 2025-03-26 03:25:35.827118+00:00
[2025-03-26T03:30:09.399+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_clickhouse', 'load_into_clickhouse', 'manual__2025-03-26T03:25:35.827118+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp3_lkdgh5']
[2025-03-26T03:30:09.404+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask load_into_clickhouse
[2025-03-26T03:30:09.409+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1472) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T03:30:09.410+0000] {standard_task_runner.py:63} INFO - Started process 1485 to run task
[2025-03-26T03:30:09.476+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T03:25:35.827118+00:00 [running]> on host 7ea2041f8442
[2025-03-26T03:30:09.594+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_into_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T03:25:35.827118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T03:25:35.827118+00:00'
[2025-03-26T03:30:09.595+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T03:30:09.666+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-03-26T03:30:19.517+0000] {logging_mixin.py:188} INFO - âœ… Downloaded from S3: /tmp/all_college_data.json
[2025-03-26T03:30:19.724+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T03:30:19.725+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'latest.student.retention_rate.overall'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 153, in load_into_clickhouse
    df["latest.student.retention_rate.overall"] = df["latest.student.retention_rate.overall"].astype(float)
                                                  ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'latest.student.retention_rate.overall'
[2025-03-26T03:30:19.746+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_s3_to_clickhouse, task_id=load_into_clickhouse, run_id=manual__2025-03-26T03:25:35.827118+00:00, execution_date=20250326T032535, start_date=20250326T033009, end_date=20250326T033019
[2025-03-26T03:30:19.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task load_into_clickhouse ('latest.student.retention_rate.overall'; 1485)
[2025-03-26T03:30:19.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-26T03:30:19.836+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T03:30:19.841+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
