[2025-03-26T01:29:02.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T01:29:02.317+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T01:20:44.077133+00:00 [queued]>
[2025-03-26T01:29:02.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T01:20:44.077133+00:00 [queued]>
[2025-03-26T01:29:02.328+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-26T01:29:02.348+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_into_clickhouse> on 2025-03-26 01:20:44.077133+00:00
[2025-03-26T01:29:02.359+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_clickhouse', 'load_into_clickhouse', 'manual__2025-03-26T01:20:44.077133+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp0hwag_f_']
[2025-03-26T01:29:02.365+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask load_into_clickhouse
[2025-03-26T01:29:02.368+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T01:29:02.369+0000] {standard_task_runner.py:63} INFO - Started process 285 to run task
[2025-03-26T01:29:02.432+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_s3_to_clickhouse.load_into_clickhouse manual__2025-03-26T01:20:44.077133+00:00 [running]> on host 7ea2041f8442
[2025-03-26T01:29:02.552+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_into_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T01:20:44.077133+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T01:20:44.077133+00:00'
[2025-03-26T01:29:02.553+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T01:29:02.626+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-03-26T01:29:07.541+0000] {logging_mixin.py:188} INFO - âœ… Downloaded from S3: /tmp/all_college_data.json
[2025-03-26T01:29:07.661+0000] {transform.py:105} ERROR - Error serializing column `address` into data type `String`
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 50, in _write_column_binary
    handle_error(data_conv.write_str_col(column, self.nullable, encoding, dest), ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/errors.py", line 17, in handle_error
    raise DataError(msg)
clickhouse_connect.driver.exceptions.DataError: Invalid None value in non-Nullable column, column name: `address`
[2025-03-26T01:29:07.665+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T01:29:07.666+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 135, in load_into_clickhouse
    s3_client.download_file(S3_BUCKET_NAME, S3_OBJECT_NAME, local_file)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 635, in insert
    return self.data_insert(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 280, in data_insert
    response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 472, in _raw_request
    error_handler(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/httpclient.py", line 265, in error_handler
    raise ex
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 50, in _write_column_binary
    handle_error(data_conv.write_str_col(column, self.nullable, encoding, dest), ctx)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/errors.py", line 17, in handle_error
    raise DataError(msg)
clickhouse_connect.driver.exceptions.DataError: Invalid None value in non-Nullable column, column name: `address`
[2025-03-26T01:29:07.680+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_to_s3_to_clickhouse, task_id=load_into_clickhouse, run_id=manual__2025-03-26T01:20:44.077133+00:00, execution_date=20250326T012044, start_date=20250326T012902, end_date=20250326T012907
[2025-03-26T01:29:07.704+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task load_into_clickhouse (Invalid None value in non-Nullable column, column name: `address`; 285)
[2025-03-26T01:29:07.741+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-26T01:29:07.764+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T01:29:07.769+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
